baseURL = "https://nextpertise.net/"

languageCode = "en-us"
title = ""
theme = "next"
enableRobotsTXT = true
summaryLength=25
contentdir="content/posts"
[params]
  css = ["/style.css"]
  github="https://github.com/brentstewart"
  twitter="@nextpertise"
  Authors="Brent Stewart"
[taxonomies]
  tag = "tags"
  writer = "writers"
[[menu.main]]
  name="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "TagCloud"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name="Archives"
  url="/legacy/"
  weight=4
[[menu.main]]
  name="Recent"
  url="/posts/"
  weight=3
[[menu.main]]
  name="Personal"
  url="https://stewart.tc/"
  weight=5
[[menu.main]]
  name="About"
  url = "/contributors/"
  weight = 8
[[menu.main]]
  name = "Github"
  url = "https://github.com/brentstewart"
  weight = 6